from typing import Annotated, Literal
from pydantic import BaseModel, Field
from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages

class AgentSchema(BaseModel):
    messages: Annotated[list[BaseMessage], add_messages]= Field(..., description="List of messages to be processed by the agent")
    user_question:str=Field(..., description="the original qns asked by the user")
    curated_qns:str=Field(..., description="curated user question")
    prompt_query_context:str=Field(..., description="A detailed prompt with SQL DB context that will help agent to generate SQL Query")
    generated_sql_query:str=Field(..., description="The SQL query generated by the agent based on the curated question and prompt context")
    is_safe:Literal["Yes", "No"]=Field(..., description="Indicates whether the generated SQL query is safe to execute or not")
    comments:str=Field(..., description="Additional comment or feedback from the judge regarding the SQL query")
    sql_query_execution_result:str=Field(..., description="The result of executing the generated SQL query on the database")
    final_answer:str=Field(..., description="The final answer generated by the agent based on the SQL query execution result and the curated question")


class JudgeSchema(BaseModel):
    answer:Literal["Yes", "No"]=Field(..., description="indicates whether the generated SQL query is safe or not")
    comments:str=Field(..., description="Additional comment or feedback from the judge regarding the SQL query")

class ETLAgentSchema(BaseModel):
    messages: Annotated[list[BaseMessage], add_messages]= Field(..., description="List of messages to be processed by the ETL agent")

class RouterSchema(BaseModel):
    answer:Literal["sql", "etl"]=Field(..., description="indicates wheather the user's question is related to SQL or ETL")
    comments:str=Field(..., description="additional feedback or comments regarding the classification of the user's question")

class DataAgentSchema(BaseModel):
    messages: Annotated[list[BaseMessage], add_messages]= Field(..., description="List of messages to be processed by the data agent")
    route_response : str = Field(..., description="The response from the router indicating whether to route to SQL or ETL operations")